### ISSUE TITLE
bugs or lack of understanding?

### ISSUE THREAD

**Issue by SkySem** [GTMEGA/RPLE#15]
I noticed that this incredible mod works even with shaders (at least in the screenshots provided on the development page of CurseForge), and with OptiFine - which is a great achievement in my opinion.

However, using my OptiFine_1.7.10_HD_U_E7, and some of my simple shaders - I can't achieve the effect as in the screenshots. My colored light is more likely to break..
![2024-11-12_21 16 23](https://github.com/user-attachments/assets/bb34a3e6-74bf-4b08-82c0-c52cb3c9e890)
![2024-11-12_21 16 28](https://github.com/user-attachments/assets/61b70f42-8c23-42d9-a946-616ad81fe382)

Also, if you turn on the "internal" mode in OptiFine - the world will not display colored light, or light in principle, everything will be as bright as possible (like during the day)
![2024-11-12_21 28 35](https://github.com/user-attachments/assets/6606ce83-70d8-4552-b210-8f0391b61456)
![2024-11-12_21 29 28](https://github.com/user-attachments/assets/8b3cf1f0-6cab-4f1e-84ed-5922bb28b6ce)
![2024-11-12_21 29 33](https://github.com/user-attachments/assets/98aa20ca-1d7c-403c-97e7-598e262e4df0)

Probably I'm missing some settings? Or the OptiFine version, or the right shaders? I would like some tips
 used rple last version 1.2.2
_I see something similar on two versions of laptops, on a weak one (screenshots) and on a more powerful one with a different video card. The problem occurs in both cases_

**Comment by brandyyn** [comment]
Only their modified version of BSL works with coloured lighting

**Comment by SkySem** [comment]
> Только их модифицированная версия BSL работает с цветным освещением.

oh got it, much better, but where i can find this version?

**Comment by brandyyn** [comment]
> > Только их модифицированная версия BSL работает с цветным освещением.
> 
> oh got it, much better, but where i can find this version?

In the GTMEGA modpack I think

**Comment by SkySem** [comment]
Maybe. As an option. But there is no separate version of this? :(
More precisely, so as not to download the whole set - take only the shaderpack

**Comment by brandyyn** [comment]
> Maybe. As an option. But there is no separate version of this? :( More precisely, so as not to download the whole set - take only the shaderpack

I don't know if this is up to date, i took this from when they posted the link when the mod first came out

https://cdn.discordapp.com/attachments/1140844037436346448/1141129849348563054/shaderpacks.7z?ex=6734793d&is=673327bd&hm=0ccee4f3da6084ad0d4deec91ef2b1b2cf76bbc42832742d6a9d2f7632d84d75&

**Comment by SkySem** [comment]
He-he it works 
But before installing the shader, it was necessary to assemble it a little correctly, unlike your link. But thank you very much!
![2024-11-12_22 22 39](https://github.com/user-attachments/assets/e7659bd2-ba0f-4e36-b66f-7fe84c6b3daf)
[§eBSL_v8.2.03.5d.zip](https://github.com/user-attachments/files/17722440/eBSL_v8.2.03.5d.zip) version rebuilt by me and working for minecraft. looks incredible. (sorry creator of the shader, delete me if I'm wrong)
