### ISSUE TITLE
A little bug with optifine 

### ISSUE THREAD

**Issue by SkySem** [GTMEGA/RPLE#16]
if you turn on the "internal" mode in OptiFine - the world will not display colored light, or light in principle, everything will be as bright as possible (like during the day)
![385433970-6606ce83-70d8-4552-b210-8f0391b61456](https://github.com/user-attachments/assets/48959b77-2367-4b48-b84c-3871434af035) (as normal - off)

![385433993-8b3cf1f0-6cab-4f1e-84ed-5922bb28b6ce](https://github.com/user-attachments/assets/212cd072-828c-43b9-95ca-87fc3586d066)
![385434004-98aa20ca-1d7c-403c-97e7-598e262e4df0](https://github.com/user-attachments/assets/820b25bc-6b74-48d5-9903-3e85ad12a4f0)
as day in internal

**Comment by DarianLStephens** [comment]
Internal is a shader pack, it needs to be modified the same way to work with colored light.

**Comment by SkySem** [comment]
Okay, this clarifies the situation
This shader is important because it affects several things:
- Correct position of shadows for models from modifications
- Color map of ambient light from texture pack (and for light source, but it can be a problem)
- Can help either optimize image rendering by lowering display quality, or add anti-aliasing for more durable computers

It is insignificant and small, as a rule, but it really affects the picture

**Comment by FalsePattern** [comment]
The Internal shader is not supported at the moment, it uses a different loading system from regular shaders. I will remove the button in the next update.

**Comment by SkySem** [comment]
on the one hand, it's a solution, but on the other hand, it's a very important shader, at least for displaying custom or modded models, when the model renders shadows and lights incorrectly (light - at the bottom, dark - at the top.) If there really are no alternative solutions other than removing these shaders from optifine, then okay, it's a pity that it is so

**Comment by FalsePattern** [comment]
Eventually I will bundle a base vanilla-style shader with RPLE that will be usable as a replacement for the Internal shader

**Comment by SkySem** [comment]
Hooray! I love you dude

**Comment by FalsePattern** [comment]
Fixed in 1.4.0
