### ISSUE TITLE
Red particles in mods 

### ISSUE THREAD

**Issue by SkySem** [GTMEGA/RPLE#17]
If you install Ars Magica2  in the game, then the particles of this mod will become red
![2024-11-13_14 37 44](https://github.com/user-attachments/assets/d561324d-90d6-4ff6-9417-054c6c6b1f8c)

Also i have same effect with snow, but honestly i have no idea of reason of this (that's happen without ars magica 2)
![2024-11-13_19 37 16](https://github.com/user-attachments/assets/8c3a30da-40bd-4b06-afd2-33e4e56607cd)

**Comment by brandyyn** [comment]
Same issue https://media.discordapp.net/attachments/989216736047947817/1305301528927539270/image.png?ex=6735d407&is=67348287&hm=ac82ea353e4344332501cb6ba57e329419f107b6dd9ef3e41b74131823465b49&

**Comment by SkySem** [comment]
where are you find lumi 1.0.3? we have only 1.0.2 in github \ curse

**Comment by brandyyn** [comment]
> where are you find lumi 1.0.3? we have only 1.0.2 in github \ curse

It’s 1.0.2 afaik, I just renamed it because I already had it and got sent another and wasn’t sure if it was different or not

**Comment by DarianLStephens** [comment]
Ars Magica's particles are fixed, but vanilla weather still isn't.
Can be worked around by installing something like Fancy Block Particles for its particle-based weather, but it would be nice to see this properly fixed.
It's been a problem in every iteration of colored lights up to this point.

**Comment by SkySem** [comment]
unfortunately no changes in Ars Magica 2
![2024-12-07_13 35 31](https://github.com/user-attachments/assets/d1347917-9be8-4575-aa36-bcd9b2d3e132)

versions:
rple-mc1.7.10-1.3.5
lumi-mc1.7.10-1.0.2
falsetweaks-mc1.7.10-3.7.1
falsepatternlib-mc1.7.10-1.5.4
chunkapi-mc1.7.10-0.5.2
![2024-12-07_13 35 31](https://github.com/user-attachments/assets/8f6e476b-37f5-447b-a4d8-40a9f3937f07)

UniMixins 0.1.19

and other items from my mods folder, what could have influenced
OptiFine_1.7.10_HD_U_E7

**Comment by brandyyn** [comment]
![image](https://github.com/user-attachments/assets/82d60625-12da-4893-a70b-5bd90c0db35f)

**Comment by FalsePattern** [comment]
Red snow is fixed in the next update. For the red Ars Magica 2 particles, go to `rple.cfg`, `debug` category, set `logMode=CUSTOM` and `cookieMonster=true`, and then send a snipped of the `fml_client_latest.log` file where it spams warnings `Illegal brightness value ...`

**Comment by SkySem** [comment]
Hiii!
[fml-client-latest.log](https://github.com/user-attachments/files/18244402/fml-client-latest.log)
![2024-12-25_09 52 02](https://github.com/user-attachments/assets/6589e025-2f75-4212-82d0-1ec9761a60ed)

**Comment by FalsePattern** [comment]
User error, do not rename mod jars, my mods use them for mod detection.
![image](https://github.com/user-attachments/assets/23b3f8b1-3023-4f7c-9831-eb810f80e247)
![image](https://github.com/user-attachments/assets/13812e3e-0f46-4aa5-bfe6-1709c69251f3)
