### ISSUE TITLE
[Hardcore Darkness] Dark Nether has no lighting

### ISSUE THREAD

**Issue by DarianLStephens** [GTMEGA/RPLE#19]
Dark Nether enabled:
![2024-11-15_15 33 56](https://github.com/user-attachments/assets/2e302fe7-3c7b-4ab6-a95a-501f145db3fb)
Dark Nether disabled:
![2024-11-15_15 34 11](https://github.com/user-attachments/assets/48da9389-60c4-4699-a13b-aded644ff1c9)

Also, oddly, it seems that there's still texture visible, even with it enabled. Shouldn't it be pure black, save for maybe the fog?
It appears that setting it to 'BlockOnly' or 'Both' makes things properly dark in the Nether, but 'DynamicMoonlight' keeps some minimum level of light.

**Comment by DarianLStephens** [comment]
Just double-checked with only RPLE and requirements installed, same thing:

![2024-11-15_15 41 53](https://github.com/user-attachments/assets/2d0e0ee1-6287-4008-9d8e-ee8ffc866f43)
![2024-11-15_15 42 21](https://github.com/user-attachments/assets/c0c4a380-fc82-4386-a819-1cc3db35a523)

**Comment by FalsePattern** [comment]
Fixed in 1.3.5
