### ISSUE TITLE
Logical question about config color

### ISSUE THREAD

**Issue by SkySem** [GTMEGA/RPLE#20]
In what format are colors actually written? And how can I set my custom color from the conditional color picker? I see that it is possible, but I don't understand what kind of entry the config expects from me.
![изображение](https://github.com/user-attachments/assets/8b1e0d6e-1e64-4369-ab4d-e6be047b1724)
the formats that I find on the Internet on this issue are not suitable in terms of the number or composition of the numbers. So how can I set my own color? (without testing God's luck by choosing symbols🤔?)

**Comment by brandyyn** [comment]
i believe this is how:
![image](https://github.com/user-attachments/assets/3a637f67-f2f1-49db-ba92-9edab35ca801)

**Comment by SkySem** [comment]
Oh this is definitely useful information. but there is still a mystery. I don't understand yet

**Comment by SkySem** [comment]
still opened

**Comment by brandyyn** [comment]
> still opened

you already got your answer, use logical thinking

**Comment by SkySem** [comment]
The realization finally reached me.
Roughly speaking - every second symbol that is responsible for the color in the HEX format is crossed out.

0x is not changed. But the remaining 3 symbols will be responsible for the color. At first I did not understand and then how I understood! Here are examples for future generations who will look for an answer to the question..

![изображение](https://github.com/user-attachments/assets/6b40d9f0-863c-411f-b6a1-52d737b5817a)
![изображение](https://github.com/user-attachments/assets/1431dc94-6874-4f57-bd7c-7b58edf5ba41)
